spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"

management:
  tracing:
    sampling:
      probability: 1.0